package hospitalModule;

/**
* hospitalModule/HospitalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hospitalModule.idl
* Sunday, October 27, 2019 2:11:42 o'clock PM EDT
*/

public final class HospitalHolder implements org.omg.CORBA.portable.Streamable
{
  public hospitalModule.Hospital value = null;

  public HospitalHolder ()
  {
  }

  public HospitalHolder (hospitalModule.Hospital initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hospitalModule.HospitalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hospitalModule.HospitalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hospitalModule.HospitalHelper.type ();
  }

}
