package hospitalModule;


/**
* hospitalModule/HospitalHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hospitalModule.idl
* Sunday, October 27, 2019 2:11:42 o'clock PM EDT
*/

abstract public class HospitalHelper
{
  private static String  _id = "IDL:hospitalModule/Hospital:1.0";

  public static void insert (org.omg.CORBA.Any a, hospitalModule.Hospital that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static hospitalModule.Hospital extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (hospitalModule.HospitalHelper.id (), "Hospital");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static hospitalModule.Hospital read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HospitalStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, hospitalModule.Hospital value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static hospitalModule.Hospital narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof hospitalModule.Hospital)
      return (hospitalModule.Hospital)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      hospitalModule._HospitalStub stub = new hospitalModule._HospitalStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static hospitalModule.Hospital unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof hospitalModule.Hospital)
      return (hospitalModule.Hospital)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      hospitalModule._HospitalStub stub = new hospitalModule._HospitalStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
