package hospitalModule;


/**
* hospitalModule/Hospital.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hospitalModule.idl
* Sunday, October 27, 2019 2:11:42 o'clock PM EDT
*/

public interface Hospital extends HospitalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hospital
